"""Add slug to notes

Revision ID: e44fca4f63c0
Revises: 80cd73b5e257
Create Date: 2025-01-20 22:43:47.667923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44fca4f63c0'
down_revision: Union[str, None] = '80cd73b5e257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_notes_slug'), 'notes', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_slug'), table_name='notes')
    op.drop_column('notes', 'slug')
    # ### end Alembic commands ###
